---
abstract: 'An attempt to provide a solution to avoid routine IO chores.'
author:
  - 'Kranti Konganti <konganti@tamu.edu>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: IO-Routine
requires:
  Carp: 0
  Cwd: 0
  Exporter: 0
  Module::Load: 0
  Pod::Usage: 0
  Time::HiRes: 0
  strict: 0
  warnings: 0
version: 0.38
